/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remoteBash.h"

bash_result execute_command(char *command) {
    bash_result result;

    FILE *filePipe;

    char path[1025]; //our buffer

    char *stdOut = NULL; //text result

    filePipe = popen(command, "r"); //open pipe stream with our command and capture it stdout

    if (!filePipe) {
        printf("Command execution failed!\n");

        result.status = 1;

        result.stdOut = "Command execution failed!";

        return result;
    }

    printf("Reading ... ");

    //while there are any characters in stream left, get by bufferSize (path)
    while ((fgets(path, sizeof(path) - 1, filePipe)) != NULL) {
        printf("\n%s", path); //print current block

        size_t lengthUntilNow = stdOut ? strlen(stdOut) : 0;
        stdOut = realloc(stdOut, lengthUntilNow + strlen(path) + (stdOut ? 0 : 1));
        strncpy(stdOut + lengthUntilNow, path, strlen(path) + 1);
    }
    result.status = WEXITSTATUS(pclose(filePipe));

    result.stdOut = stdOut ? stdOut : "";

    return result;
}

bash_result *rpcbash_1_svc(char **argp, struct svc_req *rqstp) {
    static bash_result result;

    printf("%s\n", *argp); //print command from client

    result = execute_command(*argp); //call command exec

    return &result; //return result or error
}