/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTEBASH_H_RPCGEN
#define _REMOTEBASH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct bash_result {
	int status;
	char *stdOut;
};
typedef struct bash_result bash_result;

#define RemoteBash 0x23451111
#define VERSIO 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpcbash 1
extern  bash_result * rpcbash_1(char **, CLIENT *);
extern  bash_result * rpcbash_1_svc(char **, struct svc_req *);
extern int remotebash_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpcbash 1
extern  bash_result * rpcbash_1();
extern  bash_result * rpcbash_1_svc();
extern int remotebash_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bash_result (XDR *, bash_result*);

#else /* K&R C */
extern bool_t xdr_bash_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMOTEBASH_H_RPCGEN */
