/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remoteBash.h"

bash_result *remotebash_1(char *host, char *command) {
    CLIENT *clnt;

    bash_result *result_1;

#ifndef    DEBUG
    clnt = clnt_create(host, RemoteBash, VERSIO, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif    /* DEBUG */

    result_1 = rpcbash_1(&command, clnt);
    if (result_1 == (bash_result *) NULL) {
        clnt_perror(clnt, "call failed");
    }
#ifndef    DEBUG
    clnt_destroy(clnt);
#endif     /* DEBUG */

    return result_1; //return result of command
}


int main(int argc, char *argv[]) {
    char *host;

    bash_result *result;

    char *command;

    if (argc < 3) { //we have 3 args file host command
        printf("usage: %s server_host \"command to execute\"\n", argv[0]);
        exit(1);
    }

    host = argv[1]; //take host first argument

    command = strdup(argv[2]); //take bash command second argument

    result = remotebash_1(host, command); //call

    free(command); //deallocate memory

    printf("exit code: %d\nstdout:\n %s", result->status, result->stdOut);

    exit(0);
}
