/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remoteBash.h"

bool_t
xdr_bash_result (XDR *xdrs, bash_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->stdOut, ~0))
		 return FALSE;
	return TRUE;
}
